create table "public"."report_reasons" (
    "reason" text not null,
    "owner_only" boolean not null default false
);


alter table "public"."report_reasons" enable row level security;

create table "public"."review_reports" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "review_id" uuid not null,
    "reporter_id" uuid not null,
    "reason" text not null,
    "explanation" text not null
);


alter table "public"."review_reports" enable row level security;

CREATE UNIQUE INDEX report_reasons_pkey ON public.report_reasons USING btree (reason);

CREATE UNIQUE INDEX review_reports_pkey ON public.review_reports USING btree (id);

alter table "public"."report_reasons" add constraint "report_reasons_pkey" PRIMARY KEY using index "report_reasons_pkey";

alter table "public"."review_reports" add constraint "review_reports_pkey" PRIMARY KEY using index "review_reports_pkey";

alter table "public"."review_reports" add constraint "public_review_reports_reason_fkey" FOREIGN KEY (reason) REFERENCES report_reasons(reason) not valid;

alter table "public"."review_reports" validate constraint "public_review_reports_reason_fkey";

alter table "public"."review_reports" add constraint "public_review_reports_review_id_fkey" FOREIGN KEY (review_id) REFERENCES reviews(review_id) not valid;

alter table "public"."review_reports" validate constraint "public_review_reports_review_id_fkey";

grant delete on table "public"."report_reasons" to "anon";

grant insert on table "public"."report_reasons" to "anon";

grant references on table "public"."report_reasons" to "anon";

grant select on table "public"."report_reasons" to "anon";

grant trigger on table "public"."report_reasons" to "anon";

grant truncate on table "public"."report_reasons" to "anon";

grant update on table "public"."report_reasons" to "anon";

grant delete on table "public"."report_reasons" to "authenticated";

grant insert on table "public"."report_reasons" to "authenticated";

grant references on table "public"."report_reasons" to "authenticated";

grant select on table "public"."report_reasons" to "authenticated";

grant trigger on table "public"."report_reasons" to "authenticated";

grant truncate on table "public"."report_reasons" to "authenticated";

grant update on table "public"."report_reasons" to "authenticated";

grant delete on table "public"."report_reasons" to "service_role";

grant insert on table "public"."report_reasons" to "service_role";

grant references on table "public"."report_reasons" to "service_role";

grant select on table "public"."report_reasons" to "service_role";

grant trigger on table "public"."report_reasons" to "service_role";

grant truncate on table "public"."report_reasons" to "service_role";

grant update on table "public"."report_reasons" to "service_role";

grant delete on table "public"."review_reports" to "anon";

grant insert on table "public"."review_reports" to "anon";

grant references on table "public"."review_reports" to "anon";

grant select on table "public"."review_reports" to "anon";

grant trigger on table "public"."review_reports" to "anon";

grant truncate on table "public"."review_reports" to "anon";

grant update on table "public"."review_reports" to "anon";

grant delete on table "public"."review_reports" to "authenticated";

grant insert on table "public"."review_reports" to "authenticated";

grant references on table "public"."review_reports" to "authenticated";

grant select on table "public"."review_reports" to "authenticated";

grant trigger on table "public"."review_reports" to "authenticated";

grant truncate on table "public"."review_reports" to "authenticated";

grant update on table "public"."review_reports" to "authenticated";

grant delete on table "public"."review_reports" to "service_role";

grant insert on table "public"."review_reports" to "service_role";

grant references on table "public"."review_reports" to "service_role";

grant select on table "public"."review_reports" to "service_role";

grant trigger on table "public"."review_reports" to "service_role";

grant truncate on table "public"."review_reports" to "service_role";

grant update on table "public"."review_reports" to "service_role";

create policy "Enable read access for all users"
on "public"."review_reports"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."report_reasons"
as permissive
for select
to public
using (true);