# On each pull request, run the supabse tests to verify the backend schema
name: Backend Tests
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
        
      - name: run tests
        run: |
          cd packages/supabase
          supabase db start
          supabase test db
