# On each pull request, run end-to-end tests using Playwright
name: End to End Tests
on:
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: preview

    env:
      CI                            : true
      TURBO_TOKEN                   : ${{ secrets.TURBO_TOKEN                }}
      TURBO_TEAM                    : ${{ vars.TURBO_TEAM                    }}
      NEXT_PUBLIC_SUPABASE_URL      : ${{ vars.NEXT_PUBLIC_SUPABASE_URL      }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY : ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_KEY          : ${{ secrets.SUPABASE_SERVICE_KEY       }}
      NEXT_PUBLIC_PUBLIC_SITE_URL   : ${{ vars.NEXT_PUBLIC_PUBLIC_SITE_URL   }}
      EDGE_CONFIG                   : ${{ vars.EDGE_CONFIG                   }}
      ADMIN_ENCRYPTION_KEY          : ${{ vars.ADMIN_ENCRYPTION_KEY          }}
      ADMIN_PASSWORD_HASH           : ${{ vars.ADMIN_PASSWORD_HASH           }}
      VERCEL_TEAM_ID                : ${{ vars.VERCEL_TEAM_ID                }}
      VERCEL_API_KEY                : ${{ vars.VERCEL_API_KEY                }}
      FLAGS_SECRET                  : ${{ vars.FLAGS_SECRET                  }}
      VERCEL_ENV                    : ${{ vars.VERCEL_ENV                    }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: |
        cd playwright-tests
        pnpm exec playwright install
        pnpx playwright install --with-deps

    - name: start supabase
      run: pnpm start:supabase

    - name: Run Playwright tests
      run: pnpm test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-tests/playwright-report/
        retention-days: 30
