# On merging to production branch, push migrations to production supabase deployment
name: Deploy Migrations to Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy migrations to production
        run: |
          cd packages/supabase
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push